#############################################################################
# Makefile for building: ToDoList
# Generated by qmake (2.01a) (Qt 4.7.4) on: Sun Jan 22 22:41:15 2012
# Project:  ToDoList.pro
# Template: app
# Command: /usr/share/qt/bin/qmake -spec /usr/local/Trolltech/Qt-4.7.4/mkspecs/linux-g++-32 -o Makefile ToDoList.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_DECLARATIVE_LIB -DQT_XMLPATTERNS_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m32 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m32 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.7.4/mkspecs/linux-g++-32 -I. -I/usr/local/Trolltech/Qt-4.7.4/include/QtCore -I/usr/local/Trolltech/Qt-4.7.4/include/QtGui -I/usr/local/Trolltech/Qt-4.7.4/include/QtOpenGL -I/usr/local/Trolltech/Qt-4.7.4/include/QtXmlPatterns -I/usr/local/Trolltech/Qt-4.7.4/include/QtDeclarative -I/usr/local/Trolltech/Qt-4.7.4/include -I/usr/include -I.
LINK          = g++
LFLAGS        = -m32 -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/Qt-4.7.4/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.7.4/lib -L/usr/X11R6/lib -lQtDeclarative -L/usr/local/Trolltech/Qt-4.7.4/lib -lQtScript -lQtSvg -L/usr/X11R6/lib -lQtSql -lQtXmlPatterns -lQtNetwork -lQtOpenGL -lQtGui -lQtCore -lGLU -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/share/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Main.cpp \
		TodoItem.cpp \
		TodoList.cpp \
		DBList.cpp \
		DBListFile.cpp moc_TodoList.cpp
OBJECTS       = Main.o \
		TodoItem.o \
		TodoList.o \
		DBList.o \
		DBListFile.o \
		moc_TodoList.o
DIST          = /usr/local/Trolltech/Qt-4.7.4/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/unix/opengl.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/include_source_dir.prf \
		ToDoList.pro
QMAKE_TARGET  = ToDoList
DESTDIR       = 
TARGET        = ToDoList

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ToDoList.pro  /usr/local/Trolltech/Qt-4.7.4/mkspecs/linux-g++-32/qmake.conf /usr/local/Trolltech/Qt-4.7.4/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/unix/opengl.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-4.7.4/lib/libQtDeclarative.prl \
		/usr/local/Trolltech/Qt-4.7.4/lib/libQtScript.prl \
		/usr/local/Trolltech/Qt-4.7.4/lib/libQtCore.prl \
		/usr/local/Trolltech/Qt-4.7.4/lib/libQtSvg.prl \
		/usr/local/Trolltech/Qt-4.7.4/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-4.7.4/lib/libQtSql.prl \
		/usr/local/Trolltech/Qt-4.7.4/lib/libQtXmlPatterns.prl \
		/usr/local/Trolltech/Qt-4.7.4/lib/libQtNetwork.prl \
		/usr/local/Trolltech/Qt-4.7.4/lib/libQtOpenGL.prl
	$(QMAKE) -spec /usr/local/Trolltech/Qt-4.7.4/mkspecs/linux-g++-32 -o Makefile ToDoList.pro
/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/g++.conf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/unix/opengl.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-4.7.4/lib/libQtDeclarative.prl:
/usr/local/Trolltech/Qt-4.7.4/lib/libQtScript.prl:
/usr/local/Trolltech/Qt-4.7.4/lib/libQtCore.prl:
/usr/local/Trolltech/Qt-4.7.4/lib/libQtSvg.prl:
/usr/local/Trolltech/Qt-4.7.4/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-4.7.4/lib/libQtSql.prl:
/usr/local/Trolltech/Qt-4.7.4/lib/libQtXmlPatterns.prl:
/usr/local/Trolltech/Qt-4.7.4/lib/libQtNetwork.prl:
/usr/local/Trolltech/Qt-4.7.4/lib/libQtOpenGL.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Trolltech/Qt-4.7.4/mkspecs/linux-g++-32 -o Makefile ToDoList.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/ToDoList1.0.0 || $(MKDIR) .tmp/ToDoList1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/ToDoList1.0.0/ && $(COPY_FILE) --parents TodoList.h TodoItem.h DBText.h DBList.h DBListFile.h .tmp/ToDoList1.0.0/ && $(COPY_FILE) --parents Main.cpp TodoItem.cpp TodoList.cpp DBList.cpp DBListFile.cpp .tmp/ToDoList1.0.0/ && (cd `dirname .tmp/ToDoList1.0.0` && $(TAR) ToDoList1.0.0.tar ToDoList1.0.0 && $(COMPRESS) ToDoList1.0.0.tar) && $(MOVE) `dirname .tmp/ToDoList1.0.0`/ToDoList1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/ToDoList1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_TodoList.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_TodoList.cpp
moc_TodoList.cpp: TodoItem.h \
		TodoList.h
	/usr/local/Trolltech/Qt-4.7.4/bin/moc $(DEFINES) $(INCPATH) TodoList.h -o moc_TodoList.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

Main.o: Main.cpp TodoItem.h \
		TodoList.h \
		DBList.h \
		DBListFile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Main.o Main.cpp

TodoItem.o: TodoItem.cpp TodoItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TodoItem.o TodoItem.cpp

TodoList.o: TodoList.cpp TodoList.h \
		TodoItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TodoList.o TodoList.cpp

DBList.o: DBList.cpp DBList.h \
		TodoItem.h \
		TodoList.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DBList.o DBList.cpp

DBListFile.o: DBListFile.cpp DBListFile.h \
		DBList.h \
		TodoItem.h \
		TodoList.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DBListFile.o DBListFile.cpp

moc_TodoList.o: moc_TodoList.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TodoList.o moc_TodoList.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

